feat(client): Enable PWA
TBS1996/ocean-chat pull request #77
Opened 2024-06-15 13:50 UTC by TBS1996

- **wip**
- **wip**

2024-06-15 16:30 UTC, neeleshpoli requested changes
Noticed a few small issues

2024-06-15 16:30 UTC, neeleshpoli commented on assets/manifest.json
> +  "start_url": "/index.html",
I believe that the `start_url` should be just `/`

2024-06-15 16:30 UTC, neeleshpoli commented on assets/sw.js
The browser only checks for service worker updates every 24 hours, maybe a better update mechanism would be someone we should consider.

2024-06-15 16:30 UTC, neeleshpoli commented on assets/sw.js
> +var offlineFundamentals = [
We should probably cache the home page so that people with slower internet speeds can launch and load the app faster.

2024-06-15 16:30 UTC, neeleshpoli commented on index.html
> +<html>
Adding the lang attribute here would be a good idea, especially for accessibility reasons.

2024-06-16 13:59 UTC, neeleshpoli commented on assets/sw.js
The service worker will now check for any updates to itself every 4 hours.

2024-06-16 14:00 UTC, neeleshpoli approved these changes
All good to go!

2024-06-17 08:53 UTC, TBS1996 commented
perfect, thanks so much!

2024-06-17 08:54 UTC, merged